/**
 * Mock data for hackathon demo
 * In production, this would come from DynamoDB via Amplify DataStore
 */

export const mockCustomer = {
  id: "cust-001",
  email: "thandi.mokoena@email.co.za",
  fullName: "Thandi Mokoena",
  omBankAccountId: "OMB-2024-001234",
  idNumber: "8805120****",
  phoneNumber: "+27 82 555 1234",
  isEligible: true,
  eligibilityStatus: "ELIGIBLE" as const,
};

export const mockWallet = {
  id: "wallet-001",
  customerId: "cust-001",
  balance: 156.42,
  totalCashbackEarned: 412.87,
  totalPremiumsCovered: 256.45,
  monthlyEarnings: 14.32,
  monthlyCapReached: false,
  lastResetDate: "2026-07-01",
  status: "ACTIVE" as const,
};

export const mockPolicies = [
  {
    id: "pol-001",
    customerId: "cust-001",
    policyNumber: "OM-LIFE-2024-5678",
    policyType: "LIFE" as const,
    monthlyPremium: 450.0,
    premiumDueDate: 25,
    status: "ACTIVE" as const,
    lastPaidDate: "2026-06-25",
    nextDueDate: "2026-07-25",
    coverAmount: 500000.0,
    riskScore: 0.23,
  },
  {
    id: "pol-002",
    customerId: "cust-001",
    policyNumber: "OM-FUN-2024-9012",
    policyType: "FUNERAL" as const,
    monthlyPremium: 125.0,
    premiumDueDate: 28,
    status: "ACTIVE" as const,
    lastPaidDate: "2026-06-28",
    nextDueDate: "2026-07-28",
    coverAmount: 50000.0,
    riskScore: 0.12,
  },
];

export const mockTransactions = [
  {
    id: "txn-001",
    customerId: "cust-001",
    merchantName: "Pick n Pay - Sandton City",
    merchantCategory: "Grocery",
    amount: 1245.67,
    cashbackAmount: 12.46,
    cashbackApplied: true,
    transactionDate: "2026-07-06",
    cardLast4: "4523",
    status: "COMPLETED" as const,
    isParticipatingRetailer: true,
  },
  {
    id: "txn-002",
    customerId: "cust-001",
    merchantName: "Checkers - Rosebank",
    merchantCategory: "Grocery",
    amount: 876.23,
    cashbackAmount: 8.76,
    cashbackApplied: true,
    transactionDate: "2026-07-04",
    cardLast4: "4523",
    status: "COMPLETED" as const,
    isParticipatingRetailer: true,
  },
  {
    id: "txn-003",
    customerId: "cust-001",
    merchantName: "Woolworths Food - Mall of Africa",
    merchantCategory: "Grocery",
    amount: 432.10,
    cashbackAmount: 4.32,
    cashbackApplied: true,
    transactionDate: "2026-07-02",
    cardLast4: "4523",
    status: "COMPLETED" as const,
    isParticipatingRetailer: true,
  },
  {
    id: "txn-004",
    customerId: "cust-001",
    merchantName: "Engen Garage",
    merchantCategory: "Fuel",
    amount: 950.00,
    cashbackAmount: 0,
    cashbackApplied: false,
    transactionDate: "2026-07-03",
    cardLast4: "4523",
    status: "COMPLETED" as const,
    isParticipatingRetailer: false,
  },
  {
    id: "txn-005",
    customerId: "cust-001",
    merchantName: "Shoprite - Soweto",
    merchantCategory: "Grocery",
    amount: 654.89,
    cashbackAmount: 5.68,
    cashbackApplied: true,
    transactionDate: "2026-06-30",
    cardLast4: "4523",
    status: "COMPLETED" as const,
    isParticipatingRetailer: true,
  },
  {
    id: "txn-006",
    customerId: "cust-001",
    merchantName: "Spar - Midrand",
    merchantCategory: "Grocery",
    amount: 312.45,
    cashbackAmount: 3.12,
    cashbackApplied: true,
    transactionDate: "2026-06-28",
    cardLast4: "4523",
    status: "COMPLETED" as const,
    isParticipatingRetailer: true,
  },
];

export const mockWalletTransactions = [
  {
    id: "wt-001",
    walletId: "wallet-001",
    type: "CASHBACK_CREDIT" as const,
    amount: 12.46,
    description: "1% cashback - Pick n Pay Sandton City",
    referenceId: "txn-001",
    balanceAfter: 156.42,
    createdAt: "2026-07-06T14:32:00Z",
  },
  {
    id: "wt-002",
    walletId: "wallet-001",
    type: "CASHBACK_CREDIT" as const,
    amount: 8.76,
    description: "1% cashback - Checkers Rosebank",
    referenceId: "txn-002",
    balanceAfter: 143.96,
    createdAt: "2026-07-04T10:15:00Z",
  },
  {
    id: "wt-003",
    walletId: "wallet-001",
    type: "PREMIUM_DEBIT" as const,
    amount: -125.0,
    description: "Auto-cover: Funeral policy OM-FUN-2024-9012",
    referenceId: "pol-002",
    balanceAfter: 135.20,
    createdAt: "2026-06-28T08:00:00Z",
  },
  {
    id: "wt-004",
    walletId: "wallet-001",
    type: "CASHBACK_CREDIT" as const,
    amount: 4.32,
    description: "1% cashback - Woolworths Food",
    referenceId: "txn-003",
    balanceAfter: 260.20,
    createdAt: "2026-07-02T16:45:00Z",
  },
  {
    id: "wt-005",
    walletId: "wallet-001",
    type: "CASHBACK_CREDIT" as const,
    amount: 5.68,
    description: "1% cashback - Shoprite Soweto",
    referenceId: "txn-005",
    balanceAfter: 255.88,
    createdAt: "2026-06-30T09:20:00Z",
  },
];

export const mockInsights = [
  {
    id: "insight-001",
    customerId: "cust-001",
    alertType: "WALLET_COVER_APPLIED" as const,
    severity: "MEDIUM" as const,
    title: "Premium Auto-Covered",
    message:
      "Your Smart Cover Wallet automatically covered your Funeral policy premium of R125.00 last month. Your policy remains active.",
    policyId: "pol-002",
    actionTaken: true,
    actionDescription: "Auto-debited R125.00 from Smart Cover Wallet",
    isRead: true,
    expiresAt: "2026-08-01",
  },
  {
    id: "insight-002",
    customerId: "cust-001",
    alertType: "CASHBACK_MILESTONE" as const,
    severity: "LOW" as const,
    title: "You've earned over R400 in cashback!",
    message:
      "Congratulations Thandi! Your lifetime cashback has exceeded R400. Keep shopping at participating retailers to grow your safety net.",
    actionTaken: false,
    isRead: false,
    expiresAt: "2026-07-31",
  },
  {
    id: "insight-003",
    customerId: "cust-001",
    alertType: "PREMIUM_AT_RISK" as const,
    severity: "LOW" as const,
    title: "Life Premium Coming Up",
    message:
      "Your Life policy premium of R450.00 is due on 25 July. Current wallet balance: R156.42. Consider topping up through grocery shopping.",
    policyId: "pol-001",
    actionTaken: false,
    isRead: false,
    expiresAt: "2026-07-25",
  },
];

export const mockCashbackHistory = [
  { month: "Feb", amount: 18.45 },
  { month: "Mar", amount: 20.00 },
  { month: "Apr", amount: 16.78 },
  { month: "May", amount: 19.23 },
  { month: "Jun", amount: 20.00 },
  { month: "Jul", amount: 14.32 },
];

export const participatingRetailers = [
  { name: "Pick n Pay", logo: "PnP", category: "Grocery" },
  { name: "Checkers", logo: "CHK", category: "Grocery" },
  { name: "Shoprite", logo: "SHP", category: "Grocery" },
  { name: "Woolworths Food", logo: "WW", category: "Grocery" },
  { name: "Spar", logo: "SPR", category: "Grocery" },
  { name: "Food Lover's Market", logo: "FLM", category: "Grocery" },
  { name: "Makro", logo: "MKR", category: "Wholesale" },
  { name: "OK Foods", logo: "OK", category: "Grocery" },
  { name: "Boxer", logo: "BOX", category: "Grocery" },
];
